[project]
name = "backend"
version = "0.1.0"
description = "FastAPI web app backend"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi-users>=14.0.1",
    "fastapi[all]>=0.115.12",
]
