[project]
name = "backend"
version = "0.1.0"
description = "FastAPI web app backend"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi-users[sqlalchemy]>=13.0.0,<14",
    "fastapi[standard]>=0.115.0,<0.116",
]
